### PR TITLE
CSS

### PR DESCRIPTION
**Pull request by kierajreed**
Added a border to the achievements.

### CODE REVIEW

**Comment by olleharstedt** [comment]
Screenshot, please?

**Comment by kierajreed** [comment]
How do I get one of them unlocked + border?

**Comment by olleharstedt** [comment]
You mean cheating? Enter this is JavaScript console (F12):

    achData[0].owned = 1

That will unlock achievement 1.

**Comment by kierajreed** [comment]
OK, how do I run my branch?

**Comment by olleharstedt** [comment]
You need a server setup on your machine, like Apache2. Wait, maybe it's easier if I just copy-paste it to mine to test... How did you test this before?

**Comment by kierajreed** [comment]
You sent me the screenshot of the unlocked achievements.

**Comment by olleharstedt** [comment]
Ah, and you painted on that pic? Can you upload your changes to the pic?

**Comment by olleharstedt** [comment]
How it looks like for me:

Pic

**Comment by kierajreed** [comment]
Yep. Much better.

**Comment by olleharstedt** [comment]
Cool, will upload!

**Comment by olleharstedt** [comment]
Commited.

**Pull request closed without merging**
